layout_spectrum: 0.7281981
color:
  saturation: 0.3833082
  lightness: 0.7495107
  brandStrength: 0.6239104
  brandColors:
    - '#FEFEFE'
    - '#392C26'
    - '#A9B7B8'
    - '#849292'
    - '#7F6459'
  rhythmicContrast: 0.8747224
typography_spectrum: 0.4810808
name: The Wealth Stylist
